import {
  SiteMesurement,
  Category,
  Product,
  ProductType,
  Dimension,
  Units,
  DimensionXUnits,
} from './model';

export const categoryItems: Category[] = [
  { value: 'TIMBER', viewValue: 'TIMBER' },
  { value: 'GRAPES', viewValue: 'GRAPES' },
  { value: 'NECTARINES', viewValue: 'NECTARINES' },
  { value: 'PEACHES', viewValue: 'PEACHES' },
  { value: 'CRP', viewValue: 'CRP' },
];

/*
  amountInvoiced?: number;
  amountSold?: number;
*/
export const siteMesurementItems: SiteMesurement[] = [
  {
    Id: 1,
    Type: 'ACM1',
    Category: 'TIMBER',
    ProductName: 'AQUA PROD SALE',
    EstimateCapacity: 100000,
    ActualCapacity: 90000,
    Adjustments: [
      {
        Id: 1,
        FromDate: new Date('2020-12-02'),
        Capacity: 91000,
        Reason: 'Reson1',
      },
      {
        Id: 1,
        FromDate: new Date('2020-10-02'),
        Capacity: 92000,
        Reason: 'Reson2',
      },
      {
        Id: 1,
        FromDate: new Date('2019-01-02'),
        Capacity: 95000,
        Reason: 'Reson3',
      },
    ],
    Amount: 70000,
    UnitCode: 'MBF',
    Sold: 20000,
    startDate: new Date('2019-12-02'),
    endDate: new Date('2021-12-01'),
    invoices: [
      {
        id: 1,
        code: 'INV001',
        type: 'Sold',
        amountSold: 10000,
        amountInvoiced: 6000,
        date: new Date('2019-12-02'),
        rate: 600,
        dolarValue: 4.3,
      },
      {
        id: 1,
        code: 'INV002',
        type: 'Sold',
        amountSold: 10000,
        amountInvoiced: 6000,
        date: new Date('2019-12-02'),
        rate: 600,
        dolarValue: 4,
      },
    ],
    Agreements: [
      {
        Id: 1,
        Code: 'Agreement 3201',
        Sold: 10000,
        UnitCode: 'MBF',
        Rate: 600,
        Amount: 20000,
        startDate: new Date('2019-12-02'),
        endDate: new Date('2020-12-02'),
      },
      {
        Id: 2,
        Code: 'Agreement 3202',
        Sold: 5000,
        UnitCode: 'MBF',
        Rate: 600,
        Amount: 60000,
        startDate: new Date('2020-12-02'),
        endDate: new Date('2020-12-02'),
      },
      {
        Id: 3,
        Code: 'Agreement 3203',
        Sold: 5000,
        UnitCode: 'MBF',
        Rate: 600,
        Amount: 30000,
        startDate: new Date('2020-12-02'),
        endDate: new Date('2020-12-02'),
      },
    ],
  },
  {
    Id: 2,
    Type: 'ADMI',
    Category: 'TIMBER',
    ProductName: 'APPLES GALA',
    EstimateCapacity: 200000,
    ActualCapacity: 100000,
    Amount: 80000,
    UnitCode: 'MBF',
    Sold: 20000,
    startDate: new Date('2020-12-02'),
    endDate: new Date('2021-12-01'),
    invoices: [
      {
        id: 1,
        code: 'INV001',
        type: 'Sold',
        amountSold: 10000,
        amountInvoiced: 6000,
        date: new Date('2019-12-02'),
        rate: 600,
        dolarValue: 4.3,
      },
      {
        id: 1,
        code: 'INV002',
        type: 'Sold',
        amount: 10000.0,
        amountSold: 10000,
        amountInvoiced: 6000,
        date: new Date('2019-12-02'),
        rate: 600,
        dolarValue: 4,
      },
    ],
  },
  {
    Id: 3,
    Type: 'CIT2',
    Category: 'TIMBER',
    ProductName: 'APPLES PINK LADY',
    EstimateCapacity: 300000,
    ActualCapacity: 333333,
    Amount: 33410.929,
    UnitCode: 'MBF',
    Sold: 244.937834,
    startDate: new Date('2020-12-02'),
    endDate: new Date('2021-12-01'),
  },
  {
    Id: 4,
    Type: 'Z466',
    Category: 'TIMBER',
    ProductName: 'I ASPARAGUS',
    EstimateCapacity: 400000,
    ActualCapacity: 4444444,
    Amount: 742310.929,
    UnitCode: 'MBF',
    Sold: 22.9834,
    startDate: new Date('2020-12-02'),
    endDate: new Date('2021-12-01'),
  },
  {
    Id: 5,
    Type: 'JAM3',
    Category: 'TIMBER',
    ProductName: 'BARLEY',
    EstimateCapacity: 500000,
    ActualCapacity: 555555,
    Amount: 13450.929,
    UnitCode: 'MBF',
    Sold: 27.93834,
    startDate: new Date('2020-12-02'),
    endDate: new Date('2021-12-01'),
  },
];

export const dimensionItems: Dimension[] = [
  { code: 'AAAADL', description: '(no dimensions)' },
  { code: 'ACBAC', description: 'Acid/Base capacity' },
  { code: 'ACCEL', description: 'Acceleration' },
  { code: 'CAPACI', description: 'Electr. capacity' },
  { code: 'CONDUC', description: 'Conductivity' },
  { code: 'DENSI', description: 'Density' },
  { code: 'ECURR', description: 'Electr. Current' },
  { code: 'ENERGY', description: 'Energy' },
  { code: 'EVARA', description: 'Vaporization Speed' },
  { code: 'FORCE', description: 'Force' },
  { code: 'FREQU', description: 'Frequency' },
  { code: 'HYDROL', description: 'Hydrolysis rate' },
  { code: 'LENGTH', description: 'Length' },
  { code: 'LIGHT', description: 'Luminous intensity' },
  { code: 'MAGNFD', description: 'Magnet. field dens.' },
  { code: 'MASFLO', description: 'Mass flow' },
  { code: 'MASS', description: 'Mass' },
  { code: 'MASSBD', description: 'Mass coverage' },
  { code: 'MOENER', description: 'Molar energy' },
  { code: 'MOLMAS', description: 'Mole mass' },
  { code: 'MOLQU', description: 'Mole quantity' },
  { code: 'MPROPO', description: 'Mass proportion' },
  { code: 'POINTS', description: 'Points' },
  { code: 'POWER', description: 'Power' },
  { code: 'PRESS', description: 'Pressure' },
  { code: 'PROPOR', description: 'Proportion' },
  { code: 'RESIST', description: 'Elec. Resistance' },
  { code: 'SPAEQU', description: 'Spec. equivalent' },
  { code: 'SPARAD', description: 'Spec.act.radioac.sub' },
  { code: 'SPEED', description: 'Speed' },
  { code: 'SPENER', description: 'Specific energy' },
  { code: 'SPHCAP', description: 'Spec. Heat Capacity' },
  { code: 'SPREST', description: 'Sp. Elec. Resistance' },
  { code: 'STEXKZ', description: 'Dust explosion ratio' },
  { code: 'SURFAC', description: 'Area' },
  { code: 'SURFTE', description: 'Surface tension' },
  { code: 'SURINV', description: 'Inverse area' },
  { code: 'TEMP', description: 'Temperature' },
  { code: 'TEMPRT', description: 'Rate of temp. change' },
  { code: 'THCOND', description: 'Heat Conductivity' },
  { code: 'TIME', description: 'Time' },
  { code: 'TKONZ', description: 'Particle concentrat.' },
  { code: 'VISDYN', description: 'Dynamic viscosity' },
  { code: 'VISKIN', description: 'Kinematic viscosity' },
  { code: 'VOLFLO', description: 'Volume rate of flow' },
  { code: 'VOLTAG', description: 'Electr. Tension' },
  { code: 'VOLUME', description: 'Volume' },
  { code: 'VPROPO', description: 'Volume proportion' },
];

export const productTypeItems: ProductType[] = [
  { code: 'ORCH', description: 'ORCHARD RENT', unitCode: 'AC' },
  { code: 'VIN', description: 'VINEYARD RENT', unitCode: 'AC' },
  { code: 'Z013', description: 'BOUGHS', unitCode: 'LB' },
  { code: 'Z014', description: 'BRUSH', unitCode: 'BUN' },
  { code: 'Z016', description: 'NATIVE PLANTS', unitCode: 'BOX' },
  { code: 'Z020', description: 'SP FOREST SALE', unitCode: 'LB' },
  { code: 'Z022', description: 'XMAS TREES', unitCode: 'EA' },
  { code: 'Z023', description: 'YEW', unitCode: 'BOX' },
  { code: 'Z025', description: 'BERRIES', unitCode: 'LB' },
  { code: 'Z037', description: 'I MISC LB', unitCode: 'LB' },
  { code: 'Z039', description: 'I RENT', unitCode: 'AC' },
  { code: 'Z044', description: 'SEED CROP', unitCode: 'CWT' },
  { code: 'Z046', description: 'APPLES', unitCode: 'BIN' },
  { code: 'Z047', description: 'APRICOTS', unitCode: 'TON' },
  { code: 'Z048', description: 'CHERRIES', unitCode: 'TON' },
  { code: 'Z049', description: 'GRAPES', unitCode: 'TON' },
  { code: 'Z050', description: 'MISC TREE FRUIT', unitCode: 'LB' },
  { code: 'Z051', description: 'NECTARINES', unitCode: 'LB' },
  { code: 'Z054', description: 'PEACHES', unitCode: 'LB' },
  { code: 'Z055', description: 'PEARS', unitCode: 'BIN' },
  { code: 'Z060', description: 'COML REC PRCT RENT', unitCode: '%' },
  { code: 'Z061', description: 'COML REC RENT', unitCode: 'EA' },
  { code: 'Z076', description: 'RECREATION MINIMUM', unitCode: 'EA' },
  { code: 'Z089', description: 'WIND PRCT RENT', unitCode: '%' },
  { code: 'Z093', description: 'CCRP', unitCode: '%' },
  { code: 'Z094', description: 'CREP', unitCode: '%' },
  { code: 'Z095', description: 'CRP', unitCode: '%' },
  { code: 'Z096', description: 'CRP CASH', unitCode: 'AC' },
  { code: 'Z101', description: 'D GRASS', unitCode: 'TON' },
  { code: 'Z102', description: 'D HAY', unitCode: 'TON' },
  { code: 'Z103', description: 'D LEGUME', unitCode: 'CWT' },
  { code: 'Z104', description: 'D MISC', unitCode: 'LB' },
  { code: 'Z105', description: 'D OILSEED', unitCode: 'CWT' },
  { code: 'Z106', description: 'D RENT', unitCode: 'AC' },
  { code: 'Z112', description: 'X NT D LEGUME', unitCode: 'CWT' },
  { code: 'Z113', description: 'X NT OILSEED', unitCode: 'CWT' },
  { code: 'Z143', description: 'AQ CLAM', unitCode: 'LB' },
  { code: 'Z144', description: 'AQ CLAM ROY', unitCode: 'LB' },
  { code: 'Z145', description: 'AQ  HERRING', unitCode: 'LB' },
  { code: 'Z146', description: 'AQ  MUSSELLS', unitCode: 'LB' },
  { code: 'Z151', description: 'AQ  OYSTERS', unitCode: 'LB' },
  { code: 'Z152', description: 'AQ  OYSTERS/FI', unitCode: 'LB' },
  { code: 'Z153', description: 'AQ  SAL/C', unitCode: 'LB' },
  { code: 'Z154', description: 'AQ  SAL/D', unitCode: 'LB' },
  { code: 'Z155', description: 'AQ  SCALLOPS', unitCode: 'LB' },
  { code: 'Z156', description: 'AQ  SHRIMP', unitCode: 'LB' },
  { code: 'Z160', description: 'AQ GEODUCK/HARV', unitCode: 'LB' },
  { code: 'Z162', description: 'GEODUCK/TEST', unitCode: 'LB' },
  { code: 'Z224', description: 'STATE AUM', unitCode: 'AUM' },
  { code: 'Z225', description: 'FREE USE AUM', unitCode: 'AUM' },
  { code: 'Z228', description: 'COAL ROYALTY', unitCode: 'TON' },
  { code: 'Z270', description: 'MINE ROYALTY', unitCode: 'TON' },
  { code: 'Z271', description: 'O/G ROYALTY', unitCode: 'FT3' },
  { code: 'Z273', description: 'S/G/R MINIMUM', unitCode: 'TON' },
  { code: 'Z274', description: 'S/G/R SALE', unitCode: 'TON' },
  { code: 'Z487', description: 'WINE PRODUCT', unitCode: 'GLL' },
  { code: 'Z490', description: 'WIND PROD RENT', unitCode: 'MWH' },
  { code: 'Z515', description: 'RW EASE FIRE', unitCode: 'EA' },
  { code: 'Z516', description: 'S/G/R BACKFILL', unitCode: 'TON' },
  { code: 'Z517', description: 'SUNFLOWER', unitCode: 'LB' },
  { code: 'Z887', description: 'D CEREAL GRAIN', unitCode: '%' },
  { code: 'Z889', description: 'X NT D CEREAL GRN', unitCode: '%' },
  { code: 'Z891', description: 'APPLES ORGANIC', unitCode: 'BIN' },
  { code: 'Z893', description: 'CHERRIES ORGANIC', unitCode: 'TON' },
  { code: 'Z903', description: 'Prod Sale LB', unitCode: 'LB' },
  { code: 'Z905', description: 'Prod Sale TON', unitCode: 'TON' },
  { code: 'Z907', description: 'Prod Sale BIN', unitCode: 'BIN' },
  { code: 'Z909', description: 'Prod Sale EA', unitCode: 'EA' },
  { code: 'Z911', description: 'Prod Sale CUY', unitCode: 'CUY' },
  { code: 'Z913', description: 'Summerfallow', unitCode: 'AC' },
  { code: 'Z915', description: 'S/G/R Sale CUY', unitCode: 'CUY' },
  { code: 'Z917', description: 'S/G/R Minimum CUY', unitCode: 'CUY' },
  { code: 'Z969', description: 'PRODUCT SALE CWT', unitCode: 'CWT' },
  { code: 'Z970', description: 'PRODUCT SALE BUS', unitCode: 'BUS' },
  { code: 'Z981', description: 'Tree Poplar', unitCode: 'TON' },
  { code: 'Z982', description: 'CR Trees Poplar', unitCode: 'TON' },
  { code: 'Z983', description: 'Peppers', unitCode: 'TON' },
  { code: 'Z984', description: 'CR Peppers', unitCode: 'TON' },
  { code: 'Z988', description: 'RW EASE FIRE', unitCode: 'EA' },
  { code: 'Z989', description: 'CR RW EASE FIRE', unitCode: 'EA' },
  { code: 'Z990', description: 'S/G/R BACKFILL', unitCode: 'TON' },
  { code: 'Z991', description: 'CR S/G/R BACKFILL', unitCode: 'TON' },
  { code: 'ZA30', description: 'I MISC TON', unitCode: 'TON' },
  { code: 'ZA31', description: 'I MISC CWT', unitCode: 'CWT' },
  { code: 'ZA32', description: 'I MISC BUS', unitCode: 'BUS' },
];

export const productItems: Product[] = [
  {
    code: 'COAL',
    description: 'COAL',
    unitCode: 'TON',
    productTypeCode: 'Z228',
  },
  {
    code: 'CUL2',
    description: 'AQUA PROD SALE',
    unitCode: 'LB',
    productTypeCode: 'Z903',
  },
  {
    code: 'GDU2',
    description: 'GEODUCKS',
    unitCode: 'LB',
    productTypeCode: 'Z160',
  },
  {
    code: 'GRA4',
    description: 'GRAZING',
    unitCode: 'AUM',
    productTypeCode: 'Z224',
  },
  {
    code: 'GRAR',
    description: 'AUM RATE',
    unitCode: 'AUM',
    productTypeCode: 'Z224',
  },
  {
    code: 'PAST',
    description: 'PASTURE IMPROV',
    unitCode: 'AC',
    productTypeCode: 'Z106',
  },
  {
    code: 'RAN3',
    description: 'PERMIT RANGE',
    unitCode: 'AUM',
    productTypeCode: 'Z225',
  },
  {
    code: 'REC2',
    description: 'Recreation Each',
    unitCode: 'EA',
    productTypeCode: 'Z076',
  },
  {
    code: 'ROC1',
    description: 'ROCK AND STONE',
    unitCode: 'TON',
    productTypeCode: 'Z915',
  },
  {
    code: 'ROC3',
    description: 'ROCK AND STONE',
    unitCode: 'CUY',
    productTypeCode: 'Z274',
  },
  {
    code: 'SFP3',
    description: 'SP FOREST HARVEST',
    unitCode: 'BIN',
    productTypeCode: 'Z907',
  },
  {
    code: 'SFP4',
    description: 'SP FOREST HARVEST',
    unitCode: 'BOX',
    productTypeCode: 'Z016',
  },
  {
    code: 'SFP6',
    description: 'SP FOREST HARVEST',
    unitCode: 'LB',
    productTypeCode: 'Z013',
  },
  {
    code: 'SFP7',
    description: 'SP FOREST HARVEST',
    unitCode: 'BUN',
    productTypeCode: 'Z014',
  },
  {
    code: 'SFPS',
    description: 'SP FOREST HARVEST',
    unitCode: 'EA',
    productTypeCode: 'Z909',
  },
  {
    code: 'SNG7',
    description: 'SAND AND GRAVEL',
    unitCode: 'CUY',
    productTypeCode: 'Z915',
  },
  {
    code: 'SNG8',
    description: 'SAND AND GRAVEL',
    unitCode: 'TON',
    productTypeCode: 'Z274',
  },
  {
    code: 'WIN2',
    description: 'WIND PRCT RENT',
    unitCode: 'MWH',
    productTypeCode: 'Z089',
  },
  {
    code: 'Z003',
    description: 'MISC TREE FRUIT',
    unitCode: 'LB',
    productTypeCode: 'Z050',
  },
  {
    code: 'Z004',
    description: 'APPLES BRAEBURN',
    unitCode: 'BIN',
    productTypeCode: 'Z046',
  },
  {
    code: 'Z005',
    description: 'APPLES FUJI',
    unitCode: 'BIN',
    productTypeCode: 'Z046',
  },
  {
    code: 'Z006',
    description: 'APPLES GALA',
    unitCode: 'BIN',
    productTypeCode: 'Z046',
  },
  {
    code: 'Z007',
    description: 'APPLES GOLD D',
    unitCode: 'BIN',
    productTypeCode: 'Z046',
  },
  {
    code: 'Z008',
    description: 'APPLES GRANNY',
    unitCode: 'BIN',
    productTypeCode: 'Z046',
  },
  {
    code: 'Z009',
    description: 'APPLES MISC',
    unitCode: 'BIN',
    productTypeCode: 'Z046',
  },
  {
    code: 'Z010',
    description: 'APPLES PINK LADY',
    unitCode: 'BIN',
    productTypeCode: 'Z046',
  },
  {
    code: 'Z012',
    description: 'AQ SAND',
    unitCode: 'CUY',
    productTypeCode: 'Z274',
  },
  {
    code: 'Z014',
    description: 'I ASPARAGUS',
    unitCode: 'LB',
    productTypeCode: 'Z037',
  },
  {
    code: 'Z015',
    description: 'BARLEY',
    unitCode: 'TON',
    productTypeCode: 'Z887',
  },
  {
    code: 'Z016',
    description: 'X BARLEY NT',
    unitCode: 'TON',
    productTypeCode: 'Z889',
  },
  {
    code: 'Z017',
    description: 'I BEETS',
    unitCode: 'LB',
    productTypeCode: 'Z037',
  },
  {
    code: 'Z019',
    description: 'I BUCKWHEAT',
    unitCode: 'LB',
    productTypeCode: 'Z037',
  },
  {
    code: 'Z020',
    description: 'I CARROTS',
    unitCode: 'TON',
    productTypeCode: 'Z037',
  },
  {
    code: 'Z022',
    description: 'CHERRIES CHELAN',
    unitCode: 'TON',
    productTypeCode: 'Z048',
  },
  {
    code: 'Z026',
    description: 'I CILANTRO',
    unitCode: 'LB',
    productTypeCode: 'Z037',
  },
  {
    code: 'Z027',
    description: 'CLAM',
    unitCode: 'LB',
    productTypeCode: 'Z143',
  },
  {
    code: 'Z031',
    description: 'I CORN SWEET',
    unitCode: 'TON',
    productTypeCode: 'ZA30',
  },
  {
    code: 'Z032',
    description: 'I GARLIC',
    unitCode: 'TON',
    productTypeCode: 'ZA30',
  },
  {
    code: 'Z035',
    description: 'OATS',
    unitCode: 'BUS',
    productTypeCode: 'Z887',
  },
  {
    code: 'Z036',
    description: 'X OATS NT',
    unitCode: 'BUS',
    productTypeCode: 'Z889',
  },
  {
    code: 'Z037',
    description: 'STRAW',
    unitCode: 'TON',
    productTypeCode: 'Z104',
  },
  {
    code: 'Z040',
    description: 'GRAPES CAB F',
    unitCode: 'TON',
    productTypeCode: 'Z049',
  },
  {
    code: 'Z041',
    description: 'GRAPES CAB S',
    unitCode: 'TON',
    productTypeCode: 'Z049',
  },
  {
    code: 'Z042',
    description: 'GRAPES CHARD',
    unitCode: 'TON',
    productTypeCode: 'Z049',
  },
  {
    code: 'Z043',
    description: 'GRAPES MERLOT',
    unitCode: 'TON',
    productTypeCode: 'Z049',
  },
  {
    code: 'Z044',
    description: 'GRAPES MISC',
    unitCode: 'TON',
    productTypeCode: 'Z049',
  },
  {
    code: 'Z045',
    description: 'GRAPES RIESLING',
    unitCode: 'TON',
    productTypeCode: 'Z049',
  },
  {
    code: 'Z046',
    description: 'GRAPES SANGIO',
    unitCode: 'TON',
    productTypeCode: 'Z049',
  },
  {
    code: 'Z047',
    description: 'GRAPES SEMILLON',
    unitCode: 'TON',
    productTypeCode: 'Z049',
  },
  {
    code: 'Z048',
    description: 'GRAPES SYRAH',
    unitCode: 'TON',
    productTypeCode: 'Z049',
  },
  {
    code: 'Z049',
    description: 'GRASS',
    unitCode: 'TON',
    productTypeCode: 'Z101',
  },
  {
    code: 'Z050',
    description: 'D GRASS SEED',
    unitCode: 'CWT',
    productTypeCode: 'Z104',
  },
  {
    code: 'Z051',
    description: 'PEARS MISC',
    unitCode: 'BIN',
    productTypeCode: 'Z055',
  },
  {
    code: 'Z052',
    description: 'PEARS BARTLETT',
    unitCode: 'BIN',
    productTypeCode: 'Z055',
  },
  {
    code: 'Z053',
    description: 'I BARLEY',
    unitCode: 'TON',
    productTypeCode: 'ZA30',
  },
  {
    code: 'Z054',
    description: 'I BEANS',
    unitCode: 'CWT',
    productTypeCode: 'ZA31',
  },
  {
    code: 'Z055',
    description: 'I GRASS',
    unitCode: 'TON',
    productTypeCode: 'ZA30',
  },
  {
    code: 'Z056',
    description: 'I GRASS SEED',
    unitCode: 'CWT',
    productTypeCode: 'ZA31',
  },
  {
    code: 'Z057',
    description: 'I HAY',
    unitCode: 'TON',
    productTypeCode: 'ZA30',
  },
  {
    code: 'Z058',
    description: 'I PEAS',
    unitCode: 'CWT',
    productTypeCode: 'Z969',
  },
  {
    code: 'Z059',
    description: 'I WHEAT',
    unitCode: 'BUS',
    productTypeCode: 'ZA32',
  },
  {
    code: 'Z060',
    description: 'LEGUME BEANS',
    unitCode: 'CWT',
    productTypeCode: 'Z103',
  },
  {
    code: 'Z061',
    description: 'X LEGUME BEANS NT',
    unitCode: 'CWT',
    productTypeCode: 'Z112',
  },
  {
    code: 'Z062',
    description: 'LEGUME LENTILS',
    unitCode: 'CWT',
    productTypeCode: 'Z103',
  },
  {
    code: 'Z063',
    description: 'X LEGUME LENTIL NT',
    unitCode: 'CWT',
    productTypeCode: 'Z112',
  },
  {
    code: 'Z064',
    description: 'LEGUME PEAS',
    unitCode: 'CWT',
    productTypeCode: 'Z103',
  },
  {
    code: 'Z065',
    description: 'X LEGUME PEAS NT',
    unitCode: 'CWT',
    productTypeCode: 'Z112',
  },
  {
    code: 'Z070',
    description: 'NECTARINES MISC',
    unitCode: 'LB',
    productTypeCode: 'Z051',
  },
  {
    code: 'Z073',
    description: 'I MINT',
    unitCode: 'LB',
    productTypeCode: 'Z037',
  },
  {
    code: 'Z075',
    description: 'OILSEED CANOLA',
    unitCode: 'CWT',
    productTypeCode: 'Z105',
  },
  {
    code: 'Z076',
    description: 'X OILSEED CANOLA NT',
    unitCode: 'CWT',
    productTypeCode: 'Z113',
  },
  {
    code: 'Z077',
    description: 'OILSEED MUSTARD',
    unitCode: 'CWT',
    productTypeCode: 'Z105',
  },
  {
    code: 'Z078',
    description: 'X OILSEED MUSTD NT',
    unitCode: 'CWT',
    productTypeCode: 'Z113',
  },
  {
    code: 'Z079',
    description: 'I ONIONS',
    unitCode: 'TON',
    productTypeCode: 'ZA30',
  },
  {
    code: 'Z080',
    description: 'OYSTER',
    unitCode: 'LB',
    productTypeCode: 'Z151',
  },
  {
    code: 'Z081',
    description: 'PEACHES MISC',
    unitCode: 'LB',
    productTypeCode: 'Z054',
  },
  {
    code: 'Z083',
    description: 'I POTATOES',
    unitCode: 'TON',
    productTypeCode: 'ZA30',
  },
  {
    code: 'Z099',
    description: 'I SUGAR BEETS',
    unitCode: 'TON',
    productTypeCode: 'ZA30',
  },
  {
    code: 'Z100',
    description: 'SUMMERFALLOW',
    unitCode: 'AC',
    productTypeCode: 'Z913',
  },
  {
    code: 'Z103',
    description: 'WHEAT DNS',
    unitCode: 'BUS',
    productTypeCode: 'Z887',
  },
  {
    code: 'Z104',
    description: 'X WHEAT DNS NT',
    unitCode: 'BUS',
    productTypeCode: 'Z889',
  },
  {
    code: 'Z105',
    description: 'WHEAT HRW',
    unitCode: 'BUS',
    productTypeCode: 'Z887',
  },
  {
    code: 'Z106',
    description: 'X WHEAT HRW NT',
    unitCode: 'BUS',
    productTypeCode: 'Z889',
  },
  {
    code: 'Z107',
    description: 'WHEAT SWH',
    unitCode: 'BUS',
    productTypeCode: 'Z887',
  },
  {
    code: 'Z108',
    description: 'X WHEAT SWH NT',
    unitCode: 'BUS',
    productTypeCode: 'Z889',
  },
  {
    code: 'Z109',
    description: 'WHEAT WHC',
    unitCode: 'BUS',
    productTypeCode: 'Z887',
  },
  {
    code: 'Z110',
    description: 'X WHEAT WHC NT',
    unitCode: 'BUS',
    productTypeCode: 'Z889',
  },
  {
    code: 'Z144',
    description: 'WHEAT HWW',
    unitCode: 'BUS',
    productTypeCode: 'Z887',
  },
  {
    code: 'Z145',
    description: 'X WHEAT HWW NT',
    unitCode: 'BUS',
    productTypeCode: 'Z889',
  },
  {
    code: 'Z146',
    description: 'APRICOTS MISC',
    unitCode: 'TON',
    productTypeCode: 'Z047',
  },
  {
    code: 'Z147',
    description: 'APPLES RED D',
    unitCode: 'BIN',
    productTypeCode: 'Z046',
  },
  {
    code: 'Z163',
    description: 'PEARS BOSC',
    unitCode: 'BIN',
    productTypeCode: 'Z055',
  },
  {
    code: 'Z164',
    description: 'PEARS D ANJOU',
    unitCode: 'BIN',
    productTypeCode: 'Z055',
  },
  {
    code: 'Z177',
    description: 'CHERRIES BING',
    unitCode: 'TON',
    productTypeCode: 'Z048',
  },
  {
    code: 'Z178',
    description: 'CHERRIES MISC',
    unitCode: 'TON',
    productTypeCode: 'Z048',
  },
  {
    code: 'Z179',
    description: 'CHERRIES RAINIER',
    unitCode: 'TON',
    productTypeCode: 'Z048',
  },
  {
    code: 'Z180',
    description: 'CHERRIES VAN',
    unitCode: 'TON',
    productTypeCode: 'Z048',
  },
  {
    code: 'Z181',
    description: 'HAY',
    unitCode: 'TON',
    productTypeCode: 'Z102',
  },
  {
    code: 'Z182',
    description: 'HAY ALFALFA',
    unitCode: 'TON',
    productTypeCode: 'Z102',
  },
  {
    code: 'Z186',
    description: 'X TRITICALE',
    unitCode: 'BUS',
    productTypeCode: 'Z887',
  },
  {
    code: 'Z187',
    description: 'X TRITICALE NT',
    unitCode: 'BUS',
    productTypeCode: 'Z889',
  },
  {
    code: 'Z230',
    description: 'APPLES HONEY CRISP',
    unitCode: 'BIN',
    productTypeCode: 'Z046',
  },
  {
    code: 'Z231',
    description: 'APPLES JAZZ',
    unitCode: 'BIN',
    productTypeCode: 'Z046',
  },
  {
    code: 'Z232',
    description: 'APPLES PINOVA',
    unitCode: 'BIN',
    productTypeCode: 'Z046',
  },
  {
    code: 'Z233',
    description: 'APPLES ROME',
    unitCode: 'BIN',
    productTypeCode: 'Z046',
  },
  {
    code: 'Z234',
    description: 'APPLES WINTER BANANA',
    unitCode: 'BIN',
    productTypeCode: 'Z046',
  },
  {
    code: 'Z235',
    description: 'CHERRIES BENTON',
    unitCode: 'TON',
    productTypeCode: 'Z048',
  },
  {
    code: 'Z236',
    description: 'CHERRIES EARLY ROBIN',
    unitCode: 'TON',
    productTypeCode: 'Z048',
  },
  {
    code: 'Z237',
    description: 'CHERRIES LAPIN',
    unitCode: 'TON',
    productTypeCode: 'Z048',
  },
  {
    code: 'Z238',
    description: 'CHERRIES SANTINA',
    unitCode: 'TON',
    productTypeCode: 'Z048',
  },
  {
    code: 'Z239',
    description: 'CHERRIES SEQUOIA',
    unitCode: 'TON',
    productTypeCode: 'Z048',
  },
  {
    code: 'Z240',
    description: 'CHERRIES SWEETHEART',
    unitCode: 'TON',
    productTypeCode: 'Z048',
  },
  {
    code: 'Z241',
    description: 'CHERRIES TIETON',
    unitCode: 'TON',
    productTypeCode: 'Z048',
  },
  {
    code: 'Z242',
    description: 'GRAPES CINSAUT',
    unitCode: 'TON',
    productTypeCode: 'Z049',
  },
  {
    code: 'Z243',
    description: 'GRAPES COUNOISE',
    unitCode: 'TON',
    productTypeCode: 'Z049',
  },
  {
    code: 'Z244',
    description: 'GRAPES GEWURZT',
    unitCode: 'TON',
    productTypeCode: 'Z049',
  },
  {
    code: 'Z245',
    description: 'GRAPES GRENACHE',
    unitCode: 'TON',
    productTypeCode: 'Z049',
  },
  {
    code: 'Z246',
    description: 'GRAPES MOURVEDRE',
    unitCode: 'TON',
    productTypeCode: 'Z049',
  },
  {
    code: 'Z247',
    description: 'GRAPES MALBEC',
    unitCode: 'TON',
    productTypeCode: 'Z049',
  },
  {
    code: 'Z248',
    description: 'GRAPES PETITE SIRAH',
    unitCode: 'TON',
    productTypeCode: 'Z049',
  },
  {
    code: 'Z249',
    description: 'GRAPES PETIT VERDOT',
    unitCode: 'TON',
    productTypeCode: 'Z049',
  },
  {
    code: 'Z250',
    description: 'GRAPES PINOT GRIS',
    unitCode: 'TON',
    productTypeCode: 'Z049',
  },
  {
    code: 'Z251',
    description: 'GRAPES PRIMITIVO',
    unitCode: 'TON',
    productTypeCode: 'Z049',
  },
  {
    code: 'Z252',
    description: 'GRAPES SAUV BLANC',
    unitCode: 'TON',
    productTypeCode: 'Z049',
  },
  {
    code: 'Z253',
    description: 'GRAPES TEMPRANILLO',
    unitCode: 'TON',
    productTypeCode: 'Z049',
  },
  {
    code: 'Z254',
    description: 'GRAPES VIOGNIER',
    unitCode: 'TON',
    productTypeCode: 'Z049',
  },
  {
    code: 'Z255',
    description: 'GRAPES ZINFANDEL',
    unitCode: 'TON',
    productTypeCode: 'Z049',
  },
  {
    code: 'Z256',
    description: 'PEACHES FLAME CREST',
    unitCode: 'LB',
    productTypeCode: 'Z054',
  },
  {
    code: 'Z257',
    description: 'PEACHES SIERRA GEM',
    unitCode: 'LB',
    productTypeCode: 'Z054',
  },
  {
    code: 'Z258',
    description: 'PEACHES SNOW GIANT',
    unitCode: 'LB',
    productTypeCode: 'Z054',
  },
  {
    code: 'Z259',
    description: 'PEACHES SWEET DREAM',
    unitCode: 'LB',
    productTypeCode: 'Z054',
  },
  {
    code: 'Z260',
    description: 'PEACHES VALLEY SWEET',
    unitCode: 'LB',
    productTypeCode: 'Z054',
  },
  {
    code: 'Z261',
    description: 'NECTARINES AUG RED',
    unitCode: 'LB',
    productTypeCode: 'Z051',
  },
  {
    code: 'Z262',
    description: 'NECTARINES RED JULIA',
    unitCode: 'LB',
    productTypeCode: 'Z051',
  },
  {
    code: 'Z263',
    description: 'NECTARINES SEPT RED',
    unitCode: 'LB',
    productTypeCode: 'Z051',
  },
  {
    code: 'Z264',
    description: 'NECTARINES SUM BEAUT',
    unitCode: 'LB',
    productTypeCode: 'Z051',
  },
  {
    code: 'Z265',
    description: 'NECTARINES SUM BRITE',
    unitCode: 'LB',
    productTypeCode: 'Z051',
  },
  {
    code: 'Z266',
    description: 'NECTARINES SUM GRAND',
    unitCode: 'LB',
    productTypeCode: 'Z051',
  },
  {
    code: 'Z267',
    description: 'NECTARINES SUM SWEET',
    unitCode: 'LB',
    productTypeCode: 'Z051',
  },
  {
    code: 'Z268',
    description: 'NECTARINES WA PRIDE',
    unitCode: 'LB',
    productTypeCode: 'Z051',
  },
  {
    code: 'Z269',
    description: 'NECTARINES W SWEET',
    unitCode: 'LB',
    productTypeCode: 'Z051',
  },
  {
    code: 'Z270',
    description: 'APRICOTS CASSEL BRIT',
    unitCode: 'TON',
    productTypeCode: 'Z047',
  },
  {
    code: 'Z271',
    description: 'APRICOTS KATY',
    unitCode: 'TON',
    productTypeCode: 'Z047',
  },
  {
    code: 'Z272',
    description: 'APRICOTS PERFECTION',
    unitCode: 'TON',
    productTypeCode: 'Z047',
  },
  {
    code: 'Z273',
    description: 'APRICOTS RILAND',
    unitCode: 'TON',
    productTypeCode: 'Z047',
  },
  {
    code: 'Z274',
    description: 'APRICOTS RIVAL',
    unitCode: 'TON',
    productTypeCode: 'Z047',
  },
  {
    code: 'Z275',
    description: 'PEARS FORELLE',
    unitCode: 'BIN',
    productTypeCode: 'Z055',
  },
  {
    code: 'Z334',
    description: 'CHERRIES ORG BING',
    unitCode: 'TON',
    productTypeCode: 'Z893',
  },
  {
    code: 'Z335',
    description: 'BERRIES - BLUE',
    unitCode: 'LB',
    productTypeCode: 'Z025',
  },
  {
    code: 'Z336',
    description: 'BERRIES - RASP',
    unitCode: 'LB',
    productTypeCode: 'Z025',
  },
  {
    code: 'Z337',
    description: 'BERRIES - STRAW',
    unitCode: 'LB',
    productTypeCode: 'Z025',
  },
  {
    code: 'Z338',
    description: 'HAY TIMOTHY',
    unitCode: 'TON',
    productTypeCode: 'Z102',
  },
  {
    code: 'Z339',
    description: 'COWS',
    unitCode: 'AUM',
    productTypeCode: 'Z224',
  },
  {
    code: 'Z340',
    description: 'BULLS',
    unitCode: 'AUM',
    productTypeCode: 'Z224',
  },
  {
    code: 'Z341',
    description: 'YEARLINGS',
    unitCode: 'AUM',
    productTypeCode: 'Z224',
  },
  {
    code: 'Z342',
    description: 'WINERY PROD',
    unitCode: 'GLL',
    productTypeCode: 'Z487',
  },
  {
    code: 'Z343',
    description: 'WIND PROD MWH',
    unitCode: 'MWH',
    productTypeCode: 'Z490',
  },
  {
    code: 'Z344',
    description: 'O/G ROYALTY',
    unitCode: 'FT3',
    productTypeCode: 'Z271',
  },
  {
    code: 'Z345',
    description: 'CHERRIES SKEENA',
    unitCode: 'TON',
    productTypeCode: 'Z048',
  },
  {
    code: 'Z346',
    description: 'CHERRIES STOCATTO',
    unitCode: 'TON',
    productTypeCode: 'Z048',
  },
  {
    code: 'Z347',
    description: 'APRICOTS SUM SPRITE',
    unitCode: 'LB',
    productTypeCode: 'Z047',
  },
  {
    code: 'Z389',
    description: 'NECTARINES S BLUSH',
    unitCode: 'LB',
    productTypeCode: 'Z051',
  },
  {
    code: 'Z390',
    description: 'PEACHES SUMMER LADY',
    unitCode: 'LB',
    productTypeCode: 'Z054',
  },
  {
    code: 'Z391',
    description: 'PEACHES DIAM PRINCES',
    unitCode: 'LB',
    productTypeCode: 'Z054',
  },
  {
    code: 'Z392',
    description: 'PEACHES Z LADY',
    unitCode: 'LB',
    productTypeCode: 'Z054',
  },
  {
    code: 'Z393',
    description: 'GRAPES BARBERA',
    unitCode: 'TON',
    productTypeCode: 'Z049',
  },
  {
    code: 'Z429',
    description: 'APPLES ORG BRAEBURN',
    unitCode: 'BIN',
    productTypeCode: 'Z891',
  },
  {
    code: 'Z430',
    description: 'APPLES ORG FUJI',
    unitCode: 'BIN',
    productTypeCode: 'Z891',
  },
  {
    code: 'Z431',
    description: 'APPLES ORG GALA',
    unitCode: 'BIN',
    productTypeCode: 'Z891',
  },
  {
    code: 'Z432',
    description: 'APPLES ORG GOLD D',
    unitCode: 'BIN',
    productTypeCode: 'Z891',
  },
  {
    code: 'Z433',
    description: 'APPLES ORG GRANNY',
    unitCode: 'BIN',
    productTypeCode: 'Z891',
  },
  {
    code: 'Z434',
    description: 'APPLES ORG HONEY CRI',
    unitCode: 'BIN',
    productTypeCode: 'Z891',
  },
  {
    code: 'Z435',
    description: 'APPLES ORG JAZZ',
    unitCode: 'BIN',
    productTypeCode: 'Z891',
  },
  {
    code: 'Z436',
    description: 'APPLES ORG MISC',
    unitCode: 'BIN',
    productTypeCode: 'Z891',
  },
  {
    code: 'Z437',
    description: 'APPLES ORG PINK LADY',
    unitCode: 'BIN',
    productTypeCode: 'Z891',
  },
  {
    code: 'Z438',
    description: 'APPLES ORG RED D',
    unitCode: 'BIN',
    productTypeCode: 'Z891',
  },
  {
    code: 'Z439',
    description: 'APPLES ORG ROME',
    unitCode: 'BIN',
    productTypeCode: 'Z891',
  },
  {
    code: 'Z440',
    description: 'Grapes Roussane',
    unitCode: 'TON',
    productTypeCode: 'Z049',
  },
  {
    code: 'Z441',
    description: 'TREES POPLAR',
    unitCode: 'TON',
    productTypeCode: 'Z981',
  },
  {
    code: 'Z511',
    description: 'TRITICALE',
    unitCode: 'TON',
    productTypeCode: 'Z887',
  },
  {
    code: 'Z512',
    description: 'Peppers',
    unitCode: 'TON',
    productTypeCode: 'Z983',
  },
  {
    code: 'Z515',
    description: 'RW EASE FIRE',
    unitCode: 'EA',
    productTypeCode: 'Z988',
  },
  {
    code: 'Z516',
    description: 'S/G/R BACKFILL',
    unitCode: 'TON',
    productTypeCode: 'Z990',
  },
  {
    code: 'Z517',
    description: 'SUNFLOWER',
    unitCode: 'LB',
    productTypeCode: 'Z992',
  },
  {
    code: 'Z521',
    description: 'APPLES COSMIC CRISP',
    unitCode: 'BIN',
    productTypeCode: 'Z046',
  },
  {
    code: 'Z522',
    description: 'BERRIES - BLACK',
    unitCode: 'LB',
    productTypeCode: 'Z025',
  },
  {
    code: 'Z523',
    description: 'I BROCCOLI',
    unitCode: 'LB',
    productTypeCode: 'Z037',
  },
  {
    code: 'Z524',
    description: 'I Brussel Sprouts',
    unitCode: 'LB',
    productTypeCode: 'Z037',
  },
  {
    code: 'Z525',
    description: 'I Cauliflower',
    unitCode: 'LB',
    productTypeCode: 'Z037',
  },
  {
    code: 'Z526',
    description: 'I CORN FIELD',
    unitCode: 'TON',
    productTypeCode: 'ZA30',
  },
  {
    code: 'Z527',
    description: 'I MELONS',
    unitCode: 'TON',
    productTypeCode: 'ZA30',
  },
  {
    code: 'Z528',
    description: 'I PEAS GREEN',
    unitCode: 'CWT',
    productTypeCode: 'ZA31',
  },
  {
    code: 'Z529',
    description: 'I SQUASH',
    unitCode: 'LB',
    productTypeCode: 'Z037',
  },
  {
    code: 'Z530',
    description: 'I Hemp',
    unitCode: 'TON',
    productTypeCode: 'Z037',
  },
  {
    code: 'Z531',
    description: 'I HOPS',
    unitCode: 'TON',
    productTypeCode: 'Z037',
  },
];

export const typeItems: any[] = [
  'ACM2',
  'ACM2',
  'ACM2',
  'ADMI',
  'ACM1',
  'AMIN',
  'APP8',
  'AWM2',
  'AWM7',
  'AWM8',
  'CIT2',
  'CIT3',
  'CLA2',
  'CLS2',
  'CLS5',
  'CMAC',
  'CNTY',
  'COM3',
  'COML',
  'COMM',
  'CONS',
  'CRAC',
  'CRFT',
  'DOL2',
  'DRG2',
  'DRIL',
  'EAS2',
  'EAS3',
  'ELJ1',
  'ELJ2',
  'EXPL',
  'FISH',
  'FREE',
  'GDU2',
  'GDUC',
  'GNA1',
  'GPR',
  'GRAR',
  'HOME',
  'IND2',
  'IRR2',
  'JUDF',
  'LAN2',
  'LAND',
  'LIM2',
  'LNDR',
  'LU01',
  'LU02',
  'LU03',
  'LU04',
  'LVB2',
  'MET2',
  'MIL2',
  'MIL3',
  'MILW',
  'MINL',
  'MIS3',
  'MIS6',
  'MNRV',
  'NFAC',
  'NHAC',
  'NON',
  'NONC',
  'NOP2',
  'NWD2',
  'ORC4',
  'ORCH',
  'OTF2',
  'PARK',
  'PAST',
  'PDFT',
  'PEA2',
  'PL1',
  'PL2',
  'PORT',
  'PRAC',
  'RE1',
  'RES2',
  'RESU',
  'RPAC',
  'RR',
  'RR2',
  'RR3',
  'SFPL',
  'SIL2',
  'SNG2',
  'SNG5',
  'SOBL',
  'TCHM',
  'TDFM',
  'TEM4',
  'TEM5',
  'TER1',
  'TER2',
  'TESM',
  'TNFM',
  'TRA2',
  'TRA3',
  'TRAC',
  'TRE2',
  'TRE3',
  'TRE4',
  'TRES',
  'TRN2',
  'TSFM',
  'TUTI',
  'UTL3',
  'UTL4',
  'UTL5',
  'VIN',
  'WIND',
  'WLR3',
  'Z001',
  'Z006',
  'Z007',
  'Z020',
  'Z021',
  'Z022',
  'Z023',
  'Z047',
  'Z048',
  'Z054',
  'Z077',
  'Z078',
  'Z081',
  'Z096',
  'Z097',
  'Z099',
  'Z100',
  'Z102',
  'Z103',
  'Z110',
  'Z111',
  'Z135',
  'Z144',
  'Z161',
  'Z163',
  'Z170',
  'Z192',
  'Z237',
  'Z240',
  'Z360',
  'Z361',
  'Z376',
  'Z381',
  'Z383',
  'Z384',
  'Z385',
  'Z386',
  'Z407',
  'Z408',
  'Z409',
  'Z410',
  'Z411',
  'Z423',
  'Z426',
  'Z446',
  'Z447',
  'Z448',
  'Z460',
  'Z462',
  'Z463',
  'Z475',
  'Z476',
  'Z500',
  'Z501',
  'AMI3',
  'APP1',
  'APP6',
  'CBFT',
  'CIT4',
  'CLS4',
  'CMFT',
  'CRI3',
  'CRI4',
  'CRIM',
  'CUL1',
  'CUL3',
  'CVNT',
  'DOM3',
  'DOT3',
  'DRGD',
  'EAS4',
  'EAS7',
  'EASR',
  'ELJ4',
  'FIRE',
  'GER2',
  'GNA3',
  'GRA3',
  'GRSV',
  'HOU2',
  'INDU',
  'JAM1',
  'JAM2',
  'LAN4',
  'LEA5',
  'LOB2',
  'LU05',
  'LU07',
  'MINE',
  'MIS5',
  'MISC',
  'NBAC',
  'NBFT',
  'NHFT',
  'NONP',
  'OTF1',
  'PBAC',
  'PBFT',
  'PER4',
  'PER5',
  'PMFT',
  'POL2',
  'POL4',
  'PUB2',
  'PVT2',
  'PWR3',
  'RAN3',
  'RCO2',
  'REC2',
  'RES3',
  'RES5',
  'REU3',
  'REU6',
  'RMZ',
  'ROC3',
  'ROC4',
  'RPL2',
  'RUP',
  'RUP3',
  'RUP5',
  'RW2',
  'RWUT',
  'SELV',
  'SFL2',
  'SFP3',
  'SFP5',
  'SFPP',
  'SH22',
  'SNG3',
  'SPU3',
  'SPUS',
  'TER3',
  'TGFM',
  'TMHM',
  'TOTH',
  'TRAI',
  'TRAN',
  'TSSM',
  'TUT3',
  'TWFM',
  'TWHM',
  'TWLM',
  'TYCM',
  'WAT2',
  'WIN3',
  'Z004',
  'Z016',
  'Z024',
  'Z031',
  'Z043',
  'Z045',
  'Z051',
  'Z057',
  'Z065',
  'Z067',
  'Z071',
  'Z072',
  'Z094',
  'Z106',
  'Z108',
  'Z128',
  'Z130',
  'Z131',
  'Z137',
  'Z145',
  'Z147',
  'Z150',
  'Z152',
  'Z157',
  'Z159',
  'Z172',
  'Z179',
  'Z180',
  'Z183',
  'Z334',
  'Z351',
  'Z356',
  'Z358',
  'Z362',
  'Z364',
  'Z372',
  'Z374',
  'Z388',
  'Z396',
  'Z398',
  'Z404',
  'Z427',
  'Z441',
  'Z442',
  'Z451',
  'Z458',
  'Z465',
  'Z478',
  'Z488',
  'Z496',
  'Z507',
  'Z509',
  'Z510',
  'APP2',
  'APP3',
  'APP4',
  'APP5',
  'BERR',
  'BNK2',
  'CBAC',
  'CNT2',
  'CNT3',
  'COA2',
  'COMU',
  'CRI2',
  'CRP',
  'DIA2',
  'DNRO',
  'DNRR',
  'DOT4',
  'DOT5',
  'DRY',
  'EAS1',
  'FERT',
  'GRA4',
  'GRAZ',
  'GRND',
  'GRO2',
  'HABI',
  'HBAC',
  'HBFT',
  'IMPR',
  'LB',
  'LEA1',
  'LEA2',
  'LEA3',
  'LEGA',
  'LGBM',
  'LRST',
  'LWM2',
  'MRSV',
  'NDAC',
  'NFFT',
  'NOC2',
  'NONL',
  'OTHE',
  'PAR2',
  'PER1',
  'PER2',
  'POL5',
  'PUB4',
  'PUBU',
  'PVT',
  'RANG',
  'RE2',
  'REC',
  'REU2',
  'ROAD',
  'ROC1',
  'RPE',
  'RPFT',
  'RUP2',
  'RW',
  'RW3',
  'RW4',
  'RW5',
  'SFP2',
  'SFPS',
  'SH21',
  'SNG7',
  'SNG8',
  'SOB2',
  'SPP2',
  'SPP3',
  'STR2',
  'STR3',
  'THWD',
  'TLPM',
  'TMAM',
  'TPBM',
  'TRAM',
  'TRCM',
  'TRFT',
  'TRSV',
  'TUT4',
  'WATE',
  'WHAB',
  'WLEA',
  'Z008',
  'Z009',
  'Z012',
  'Z013',
  'Z015',
  'Z017',
  'Z037',
  'Z038',
  'Z040',
  'Z041',
  'Z042',
  'Z055',
  'Z056',
  'Z062',
  'Z063',
  'Z064',
  'Z070',
  'Z075',
  'Z083',
  'Z090',
  'Z104',
  'Z105',
  'Z107',
  'Z118',
  'Z119',
  'Z120',
  'Z121',
  'Z122',
  'Z123',
  'Z124',
  'Z125',
  'Z126',
  'Z127',
  'Z132',
  'Z133',
  'Z153',
  'Z154',
  'Z155',
  'Z156',
  'Z160',
  'Z168',
  'Z169',
  'Z175',
  'Z176',
  'Z177',
  'Z178',
  'Z186',
  'Z187',
  'Z190',
  'Z191',
  'Z327',
  'Z328',
  'Z329',
  'Z330',
  'Z331',
  'Z349',
  'Z353',
  'Z354',
  'Z355',
  'Z366',
  'Z367',
  'Z368',
  'Z369',
  'Z370',
  'Z371',
  'Z401',
  'Z402',
  'Z421',
  'Z456',
  'Z457',
  'Z459',
  'Z480',
  'Z503',
  'AMI2',
  'APP0',
  'APP7',
  'AWM1',
  'BNK3',
  'BNK7',
  'BOOM',
  'CCRP',
  'CLS1',
  'CLS3',
  'COM2',
  'COM4',
  'CUL2',
  'DISE',
  'DOM2',
  'DOT',
  'DOT2',
  'DRG3',
  'EAS5',
  'EAS6',
  'EXP2',
  'GNA2',
  'GROW',
  'IACR',
  'IRR',
  'IRR3',
  'JAM3',
  'LAN3',
  'LEA4',
  'LGAC',
  'LGFT',
  'LIEU',
  'LOB1',
  'LU06',
  'LWM1',
  'MIS2',
  'MIS4',
  'NDFT',
  'NWD1',
  'OGP',
  'ONG',
  'ORC2',
  'PDAC',
  'PER3',
  'PER6',
  'PLAN',
  'PMAC',
  'POL1',
  'POL3',
  'POR2',
  'PRFT',
  'PUB3',
  'PVT3',
  'PWR1',
  'PWR2',
  'RES4',
  'REU4',
  'REU5',
  'ROC2',
  'ROC5',
  'RUP4',
  'RUS2',
  'RWRD',
  'SEIP',
  'SEL2',
  'SFL3',
  'SFP6',
  'SNG1',
  'SNG4',
  'SNG6',
  'SOLR',
  'SPU2',
  'STOC',
  'STRU',
  'TAFM',
  'TBCM',
  'TBRM',
  'TCNF',
  'TEM2',
  'TEM3',
  'TEMP',
  'TPLP',
  'TPPM',
  'TRA4',
  'TUT2',
  'TUTL',
  'TWBM',
  'TWPM',
  'UTL1',
  'UTL2',
  'Z002',
  'Z005',
  'Z010',
  'Z019',
  'Z025',
  'Z027',
  'Z032',
  'Z044',
  'Z049',
  'Z052',
  'Z058',
  'Z059',
  'Z066',
  'Z068',
  'Z069',
  'Z073',
  'Z079',
  'Z095',
  'Z109',
  'Z112',
  'Z129',
  'Z136',
  'Z138',
  'Z139',
  'Z146',
  'Z158',
  'Z164',
  'Z181',
  'Z182',
  'Z184',
  'Z233',
  'Z350',
  'Z357',
  'Z359',
  'Z363',
  'Z365',
  'Z373',
  'Z375',
  'Z377',
  'Z382',
  'Z387',
  'Z397',
  'Z399',
  'Z403',
  'Z405',
  'Z425',
  'Z445',
  'Z449',
  'Z450',
  'Z455',
  'Z461',
  'Z464',
  'Z466',
  'Z477',
  'Z479',
  'Z485',
  'Z495',
  'Z502',
  'Z508',
  'Z515',
  'Z518',
];
